### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [prevayler/prevayler#20]
Hi
The following lines have cryptographic API misuses. <br> File name => core/src/main/java/org/prevayler/foundation/serialization/DESSerializer.java: Line number => 26: API name => Cipher:First parameter (with value "DES") should be any of {AES, Blowfish, DESede, PBEWithHmacSHA224AndAES_128, PBEWithHmacSHA256AndAES_128, PBEWithHmacSHA384AndAES_128, PBEWithHmacSHA512AndAES_128, PBEWithHmacSHA224AndAES_256, PBEWithHmacSHA256AndAES_256, PBEWithHmacSHA384AndAES_256, PBEWithHmacSHA512AndAES_256, RSA}<BR>

**Comment by jsampson** [comment]
DESSerializer selects either DES or DESede depending on what size key the caller passes in. We just provide it as an example to show how encryption can potentially be used for a Prevayler journal, but we hope that anyone with a serious need for encryption is choosing an appropriate algorithm themselves.
